package org.pfcoperez.dailyalgorithm.datastructures.graphs.directed

import org.scalatest.{FlatSpec, Inside, Matchers}

class DoubleLinkedListSpec extends FlatSpec with Matchers with Inside {

  import DoubleLinkedList.{Empty => DlEmpty, Node => DlNode, lastNode}
  import DoubleLinkedList.syntax._

  def toListLeftToRight[T](dl: DoubleLinkedList[T], acc: List[T] = Nil): List[T] = dl match {
    case DlEmpty => acc
    case DlNode(_, v, right) => toListLeftToRight(right, acc :+ v)
  }

  def toListRightToLeft[T](dl: DoubleLinkedList[T]): List[T] = {
    def toListFromLast(dl: DoubleLinkedList[T], acc: List[T]): List[T] = dl match {
      case DlEmpty => acc
      case DlNode(left, v, _) => toListFromLast(left, v :: acc)
    }
    toListFromLast(lastNode(dl), Nil)
  }

  val elements = 1 to 10

  "An double linked list" should "allow to be generated by appending elements" in {

    val lAppending = ((DlEmpty : DoubleLinkedList[Int]) /: elements) { (acc, element) =>
      acc :+ element
    }

    toListLeftToRight(lAppending) shouldBe elements.toList

  }

  it should "allow to be generated by prepending elements" in {

    val lPrepending = (elements :\ (DlEmpty : DoubleLinkedList[Int])) { (element, acc) =>
      element +: acc
    }

    toListLeftToRight(lPrepending) shouldBe elements.toList

  }

  it should "allow to move over it in both directions" in {

    val l = (elements :\ (DlEmpty : DoubleLinkedList[Int])) { (element, acc) =>
      element +: acc
    }

    l.right.right.right.left.headOption shouldBe Some(3)

    lastNode(l).left.right.right.headOption shouldBe None
    lastNode(l).left.right.headOption shouldBe Some(10)

  }

}
